### PR TITLE
Adding and editing project files

### PR DESCRIPTION
**Pull request by roooodcastro**
Added RVM `.ruby-version` and `.ruby-gemset` files, to use ruby `2.2.0@collab-cards`.
Added the directory `/.idea` to `.gitignore`
Added the gem `rubocop` to the Gemfile, for code quality checks.

### CODE REVIEW

**Comment by bschettino** [comment]
This PR closes Issue #9, right?

**Comment by rennanoliveira** [comment]
I was going to leave it open for a while more so we decide what else we'll use for code quality/checking

**Comment by roooodcastro** [comment]
I think we still need to decide if we're going to use Code Climate or another tool, and then add and configure it.

**Comment by rennanoliveira** [comment]
I'm up for Travis CI with Code Climate, what do you guys think of [putting them together](http://docs.travis-ci.com/user/code-climate/)?

**Comment by bschettino** [comment]
I think Travis CI + Code Climate is a great choice. Very useful and very easy to set up.

**Comment by bschettino** [comment]
And what about [Gemnasium](https://gemnasium.com/) ?

**Pull request merged**
